M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Fri 16 Aug 2024 12:49:35 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-16T12:49:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0217
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X6.8661Y-4.8644
X7.1338Y-4.8644
T2
X5.8463Y-4.1002
X5.8463Y-4.4152
T3
X6.09Y-4.87
X6.71Y-4.02
M30
