M48
; DRILL file {KiCad 8.0.5-dirty} date 2024-12-04T01:41:07-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-04T01:41:07-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-dirty
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.4114Y-2.2904
X4.4114Y-2.6053
T2
X4.4803Y-3.0
X6.1535Y-2.1142
M30
